branches:
  only:
  - master

language: node_js

sudo: false

node_js:
- '6.10'

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

install:
- npm install
- bower install

script:
- gulp build
